Repository CMU-313/spring24-nodebb-git-goons, pull requests merged in 2024-03, with the labels that each got.

#36 Adding test coverage for Endorsement
  test/posts.js
Labels: tests

#35 adding documentation file
  UserGuide.md
Labels: documentation

#38 Updating PR 33 with Typing Sanity Checks
  src/privileges/categories.js
  src/privileges/posts.js
  src/privileges/topics.js
  src/privileges/users.js
  src/user/index.js
Labels: enhancement
